name: Checks

on:
  push

jobs:
  dagger:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: PHPUnit
        uses: dagger/dagger-for-github@v5
        with:
          version: "0.19.6"
          verb: call
          args: dev test

      - name: PHP CS Fixer
        uses: dagger/dagger-for-github@v5
        with:
          version: "0.19.6"
          verb: call
          args: dev lintCheck

      - name: PHPStan
        uses: dagger/dagger-for-github@v5
        with:
          version: "0.19.6"
          verb: call
          args: dev analyze
